os: Visual Studio 2015

platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Init submodules
  - git submodule update --init --recursive


# Build it
build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

test: off
